# Use nginx as base Docker Image
FROM nginx

# OCI Labels
LABEL org.opencontainers.image.authors="Kalyan Reddy Daida"
LABEL org.opencontainers.image.title="Demo: Create Multiplatform Docker Images using Docker BuildKit and Buildx"
LABEL org.opencontainers.image.description="A Dockerfile demo illustrating Multiplatform Docker Images using Docker BuildKit and Buildx"
LABEL org.opencontainers.image.version="1.0"

# Using COPY to copy a local file
COPY index.html /usr/share/nginx/html