FROM nginx:alpine-slim
COPY index.html /usr/share/nginx/html

# OCI Labels
LABEL org.opencontainers.image.authors="Kalyan Reddy Daida"
LABEL org.opencontainers.image.title="Demo: Docker Ports usage"
LABEL org.opencontainers.image.description="A Dockerfile demo illustrating the use of the Docker Ports"
LABEL org.opencontainers.image.version="1.0"
